steps:
  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "rsync", "-x", ".*/table_definitions_kovan/.*", "-r", "-c", "-d", "./dags", "gs://${_BUCKET}/dags"]

substitutions:
 _BUCKET: your-bucket
